[package]
name = "msr-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing_subscriberserde = { version = "1", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.9"
tracing_subscriber = "0.3.19"
